name: ci/cd pipeline 1

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Устанавливаем .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  

    # Шаг 3: Восстанавливаем зависимости
    - name: Restore dependencies
      run: dotnet restore

    # Шаг 4: Компилируем приложение
    - name: Build application
      run: dotnet build --configuration Release --no-restore

    # Шаг 5: Публикуем приложение (создаем артефакты)
    - name: Publish application
      run: dotnet publish --configuration Release --no-build --output ./artifacts

    # Шаг 6: Сохраняем артефакты для использования в следующем этапе
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./artifacts/
        retention-days: 1  # Артефакты будут храниться 1 день

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    # Шаг 1: Скачиваем артефакты
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts
        path: ./artifacts/

    - name: Deploy application
      env:
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        # Останавливаем службу
        sudo systemctl stop okr_backend

        # Копируем новые файлы в рабочую директорию
        mkdir -p $DEPLOY_PATH
        cp -r ./artifacts/* $DEPLOY_PATH

        # Запускаем службу
        sudo systemctl start okr_backend

        # Проверяем статус службы (опционально)
        # sudo systemctl status okr_backend